name: Build Images
on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate cyclonedx json SBOM for git repo
        uses: scribe-security/action-bom@master
        with:
          type: git
          target: .
          format: json
          force: true
          product-key: git-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build images
        run: |
          # Build Docker image
          docker build -t airflow-image:${{ github.sha }} .

      - name: Display Docker image
        run: docker images
          
      - name: Generate cyclonedx json SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: 'airflow-image:${{ github.sha }}'
          format: json
          force: true
          product-key: image-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
      
