name: Build Images
on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build images
        run: |
          # Build Docker image
          docker build -t airflow-image:${{ github.sha }} .

      - name: Display Docker image
        run: docker images

      - name: valint install
        id: valint_install
        uses: scribe-security/action-installer@master
        with:
          tools: valint
          
      - name: Generate cyclonedx json SBOM
        uses: scribe-security/action-bom@master
        with:
          target: 'busybox:latest'
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: valint verify
        id: valint_verify
        uses: scribe-security/action-installer@master
        with:
          target: 'busybox:latest'
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
