name: Build and Release Images
on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate cyclonedx json SBOM for git repo
        uses: scribe-security/action-bom@master
        with:
          type: git
          target: .
          format: json
          product-key: airflow-git-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build images
        run: |
          # Build Docker image
          docker build -t airflow-image:${{ github.sha }} .

      - name: Display Docker image
        run: docker images

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHST }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: |
          docker tag airflow-image:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/airflow-image:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/airflow-image:${{ github.sha }}

      - name: Generate cyclonedx json SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: "ghcr.io/${{ github.repository_owner }}/airflow-image:${{ github.sha }}"
          format: json
          force: true
          product-key: airflow-image-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          title: Release ${{ github.ref }}
